/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;

/**
 *
 * @author compa
 */
public class Frm_vistaFactura extends javax.swing.JFrame {

    /**
     * Creates new form Frm_vistaFactura
     */
    public Frm_vistaFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panel_cerrarSesion = new javax.swing.JPanel();
        btn_cerrarSesion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_consulClientes = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_consulProductos = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_agregarClientes = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btn_agregarProductos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel9.add(jScrollPane3);
        jScrollPane3.setBounds(10, 150, 570, 80);

        jLabel13.setText("Detalle de la factura (Moneda dólares americanos $$)");
        jPanel9.add(jLabel13);
        jLabel13.setBounds(10, 10, 270, 14);

        jLabel14.setText("Datos del Comprador");
        jPanel9.add(jLabel14);
        jLabel14.setBounds(10, 110, 101, 14);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(null);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel10.add(jScrollPane4);
        jScrollPane4.setBounds(10, 150, 570, 80);

        jLabel15.setText("Detalle de la factura (Moneda dólares americanos $$)");
        jPanel10.add(jLabel15);
        jLabel15.setBounds(10, 10, 270, 14);

        jLabel16.setText("Datos del Comprador");
        jPanel10.add(jLabel16);
        jLabel16.setBounds(10, 110, 101, 14);

        jPanel9.add(jPanel10);
        jPanel10.setBounds(0, 0, 0, 0);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_cerrarSesion.setBackground(new java.awt.Color(51, 0, 102));

        btn_cerrarSesion.setBackground(new java.awt.Color(51, 0, 102));
        btn_cerrarSesion.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btn_cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btn_cerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cerrarSesion.setText("Cerrar Sesión");
        btn_cerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrarSesion.setName(""); // NOI18N
        btn_cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cerrarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_cerrarSesionLayout = new javax.swing.GroupLayout(panel_cerrarSesion);
        panel_cerrarSesion.setLayout(panel_cerrarSesionLayout);
        panel_cerrarSesionLayout.setHorizontalGroup(
            panel_cerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        panel_cerrarSesionLayout.setVerticalGroup(
            panel_cerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panel_cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 170, 30));

        jPanel4.setBackground(new java.awt.Color(51, 0, 102));

        btn_consulClientes.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btn_consulClientes.setForeground(new java.awt.Color(255, 255, 255));
        btn_consulClientes.setText("          Consultar Clientes          >");
        btn_consulClientes.setToolTipText("");
        btn_consulClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_consulClientes.setName(""); // NOI18N
        btn_consulClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consulClientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_consulClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_consulClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, -1));

        jPanel5.setBackground(new java.awt.Color(51, 0, 102));

        btn_consulProductos.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btn_consulProductos.setForeground(new java.awt.Color(255, 255, 255));
        btn_consulProductos.setText("          Consultar Productos       >");
        btn_consulProductos.setToolTipText("");
        btn_consulProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_consulProductos.setName(""); // NOI18N
        btn_consulProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consulProductosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_consulProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_consulProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, -1));

        jPanel6.setBackground(new java.awt.Color(51, 0, 102));

        btn_agregarClientes.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btn_agregarClientes.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregarClientes.setText("          + Agregar Clientes          >");
        btn_agregarClientes.setToolTipText("");
        btn_agregarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agregarClientes.setName(""); // NOI18N
        btn_agregarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarClientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_agregarClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_agregarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, -1));

        jPanel7.setBackground(new java.awt.Color(51, 0, 102));

        btn_agregarProductos.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btn_agregarProductos.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregarProductos.setText("          + Agregar Productos       >");
        btn_agregarProductos.setToolTipText("");
        btn_agregarProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agregarProductos.setName(""); // NOI18N
        btn_agregarProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarProductosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_agregarProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_agregarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 170, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 490));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("FACTURAR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 580, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 570, 120);

        jLabel6.setText("Detalle de la factura (Moneda dólares americanos $)");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 10, 270, 14);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel8.add(jScrollPane2);
        jScrollPane2.setBounds(10, 150, 570, 80);

        jLabel11.setText("Detalle de la factura (Moneda dólares americanos $$)");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(10, 10, 270, 14);

        jLabel12.setText("Datos del Comprador");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(10, 110, 101, 14);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(0, 0, 0, 0);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(null);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel11.add(jScrollPane5);
        jScrollPane5.setBounds(10, 150, 570, 80);

        jLabel18.setText("Datos del Comprador");
        jPanel11.add(jLabel18);
        jLabel18.setBounds(10, 110, 101, 14);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(null);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jPanel12.add(jScrollPane6);
        jScrollPane6.setBounds(10, 150, 570, 80);

        jLabel19.setText("Detalle de la factura (Moneda dólares americanos $$)");
        jPanel12.add(jLabel19);
        jLabel19.setBounds(10, 10, 270, 14);

        jLabel20.setText("Datos del Comprador");
        jPanel12.add(jLabel20);
        jLabel20.setBounds(10, 110, 101, 14);

        jPanel11.add(jPanel12);
        jPanel12.setBounds(0, 0, 0, 0);

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Cant.");
        jPanel11.add(jLabel21);
        jLabel21.setBounds(10, 10, 60, 14);

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Descripción");
        jPanel11.add(jLabel22);
        jLabel22.setBounds(240, 10, 60, 14);

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("V.Unit.");
        jPanel11.add(jLabel23);
        jLabel23.setBounds(450, 10, 50, 14);
        jPanel11.add(jTextField6);
        jTextField6.setBounds(10, 30, 60, 30);
        jPanel11.add(jTextField7);
        jTextField7.setBounds(80, 30, 360, 30);
        jPanel11.add(jTextField8);
        jTextField8.setBounds(450, 30, 50, 30);
        jPanel11.add(jTextField9);
        jTextField9.setBounds(510, 30, 50, 30);

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("V.Total.");
        jPanel11.add(jLabel24);
        jLabel24.setBounds(510, 10, 50, 14);

        jPanel3.add(jPanel11);
        jPanel11.setBounds(10, 30, 570, 70);

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel25.setText("Desarrollado por G2UNL - Derechos Reservados");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(10, 290, 230, 14);

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField10);
        jTextField10.setBounds(520, 220, 60, 19);

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField11);
        jTextField11.setBounds(520, 240, 60, 19);

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel26.setText("SUB TOTAL 12% IVA $");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(380, 240, 130, 14);

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel27.setText("SUB TOTAL $");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(380, 260, 130, 14);

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField12);
        jTextField12.setBounds(520, 260, 60, 19);

        jLabel28.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jLabel28.setText("FORMA DE PAGO");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(10, 230, 130, 14);

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField13);
        jTextField13.setBounds(520, 280, 60, 19);

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel29.setText("SUB TOTAL 0% IVA $");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(380, 220, 130, 14);

        jLabel30.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel30.setText("VALOR TOTAL $");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(380, 280, 130, 14);

        jRadioButton1.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jRadioButton1.setText("Otros");
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(330, 250, 60, 21);

        jRadioButton2.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jRadioButton2.setText("Efectivo");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(10, 250, 70, 21);

        jRadioButton3.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jRadioButton3.setText("T.Crédito/Débito");
        jPanel3.add(jRadioButton3);
        jRadioButton3.setBounds(80, 250, 110, 21);

        jRadioButton4.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jRadioButton4.setText("Depósito/Transferencia");
        jPanel3.add(jRadioButton4);
        jRadioButton4.setBounds(190, 250, 140, 21);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 590, 310));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel2.setText("CLIENTE:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 270, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel4.setText("TELEFONO DOMICILIO:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 120, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel5.setText("TELEFONO MOVIL:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 100, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel7.setText("EMAIL:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        jTextField4.setToolTipText("");
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 200, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 590, 10));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel9.setText("DIRECCIÓN COMPRADOR:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel10.setText("Datos del Comprador");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 370, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 60, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel8.setText("GUÍA REM.:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 490));

        setSize(new java.awt.Dimension(797, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_consulClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consulClientesMouseClicked
        // TODO add your handling code here:
        Frm_Clientes nuevoConsulCliente = new Frm_Clientes();
        nuevoConsulCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_consulClientesMouseClicked

    private void btn_consulProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consulProductosMouseClicked
        // TODO add your handling code here:
        Frm_Productos nuevoConsulProductos = new Frm_Productos();
        nuevoConsulProductos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_consulProductosMouseClicked

    private void btn_agregarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarClientesMouseClicked
        // TODO add your handling code here:
        Frm_agregarClientes nuevoAgregarClientes = new Frm_agregarClientes();
        nuevoAgregarClientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_agregarClientesMouseClicked

    private void btn_agregarProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarProductosMouseClicked
        // TODO add your handling code here:
        Frm_agregarProductos nuevoAgregarProductos = new Frm_agregarProductos();
        nuevoAgregarProductos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_agregarProductosMouseClicked

    private void btn_cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarSesionMouseClicked
        // TODO add your handling code here:
        Frm_vistaLogin nuevoLogin = new Frm_vistaLogin();
        nuevoLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cerrarSesionMouseClicked

    private void btn_cerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarSesionMouseEntered
        // TODO add your handling code here:
        panel_cerrarSesion.setBackground(Color.white);
       
    }//GEN-LAST:event_btn_cerrarSesionMouseEntered

    private void btn_cerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarSesionMouseExited
        // TODO add your handling code here:
        panel_cerrarSesion.setBackground(Color.blue);
        
    }//GEN-LAST:event_btn_cerrarSesionMouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_vistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_vistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_vistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_vistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_vistaFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_agregarClientes;
    private javax.swing.JLabel btn_agregarProductos;
    private javax.swing.JLabel btn_cerrarSesion;
    private javax.swing.JLabel btn_consulClientes;
    private javax.swing.JLabel btn_consulProductos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel panel_cerrarSesion;
    // End of variables declaration//GEN-END:variables
}
